import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login to Kairou 回廊',
  description: 'Generated by create next app',
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="h-[100svh] flex justify-center items-center">
      {children}
    </main>
  );
};

export default layout;
