import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import type { Metadata } from 'next';
import { Barlow_Condensed } from 'next/font/google';

const barlow = Barlow_Condensed({
  weight: ['100', '200', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Kairou 回廊',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${barlow.className} bg-clr-background-100`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
